services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  user-service:
    build: ./user-service
    container_name: user-service
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  company-service:
    build: ./company-service
    container_name: company-service
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  hub-service:
    build: ./hub-service
    container_name: hub-service
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  order-service:
    build: ./order-service
    container_name: order-service
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  operations-service:
    build: ./operations-service
    container_name: operations-service
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy