server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: order-service-route
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: company-service-route
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/company/**
          filters:
            - StripPrefix=1
        - id: delivery-service-route
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery/**
          filters:
            - StripPrefix=1
        - id: hub-service-route
          uri: lb://HUB-SERVICE
          predicates:
            - Path=/hub/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    gateway:
      enabled: true

springdoc:
  swagger-ui:
    urls:
      - name: Company Service
        url: /company/v3/api-docs
    path: /swagger-ui/index.html
