spring:
  application:
    name: delivery-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/delivering?currentSchema=delivery-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
          show_sql: true
          format_sql: true

    flyway:
      enabled: true